src/main/java/com/ll/TeamSteam/domain/user/controller/UserController.java, src/main/java/com/ll/TeamSteam/domain/user/entity/User.java, src/main/java/com/ll/TeamSteam/domain/user/repository/UserRepository.java, src/main/java/com/ll/TeamSteam/domain/user/service/UserService.java, src/main/java/com/ll/TeamSteam/global/security/SecurityConfig.java, src/main/java/com/ll/TeamSteam/global/security/SteamClient.java, src/main/java/com/ll/TeamSteam/global/security/SteamClientImpl.java, src/main/java/com/ll/TeamSteam/global/security/UserInfoResponse.java, src/main/resources/templates/main/main.html
=> Feature/6 유저 로그인 시 데이터 DB에 등록

src/main/java/com/ll/TeamSteam/domain/home/HomeController.java
=> chore : 쓸모없는 import문 제거

src/main/java/com/ll/TeamSteam/domain/user/controller/UserController.java, src/main/java/com/ll/TeamSteam/global/security/SecurityUser.java
=> ref : 시큐리티유저적용

src/main/java/com/ll/TeamSteam/domain/chatUser/entity/ChatUser.java, src/main/java/com/ll/TeamSteam/domain/matching/service/MatchingService.java, src/main/java/com/ll/TeamSteam/global/init/NotProd.java, src/main/resources/templates/chat/room.html
close #27 
채팅방 입장 시 입장메시지 버그 안나오는 거 수정하였습니다.
=> bug/27 EnterMessageBug

src/main/java/com/ll/TeamSteam/domain/chatRoom/controller/ChatRoomController.java, src/main/java/com/ll/TeamSteam/domain/chatRoom/service/ChatRoomService.java, src/main/java/com/ll/TeamSteam/domain/notification/controller/NotificationController.java, src/main/java/com/ll/TeamSteam/domain/notification/entity/Notification.java, src/main/java/com/ll/TeamSteam/domain/notification/eventListener/NotificationEventListener.java, src/main/java/com/ll/TeamSteam/domain/notification/repository/NotificationRepository.java, src/main/java/com/ll/TeamSteam/domain/notification/service/NotificationService.java, src/main/java/com/ll/TeamSteam/domain/user/service/UserService.java, src/main/java/com/ll/TeamSteam/global/event/EventAfterInvite.java, src/main/resources/templates/chat/inviteList.html, src/main/resources/templates/chat/room.html, src/main/resources/templates/common/layout.html, src/main/resources/templates/main/home.html, src/main/resources/templates/notification/list.html
=> Feature/29 초대 기능 구현

src/main/java/com/ll/TeamSteam/domain/chatRoom/controller/ChatRoomController.java, src/main/java/com/ll/TeamSteam/domain/chatRoom/service/ChatRoomService.java, src/main/java/com/ll/TeamSteam/domain/notification/controller/NotificationController.java, src/main/java/com/ll/TeamSteam/domain/notification/entity/Notification.java, src/main/java/com/ll/TeamSteam/domain/notification/eventListener/NotificationEventListener.java, src/main/java/com/ll/TeamSteam/domain/notification/repository/NotificationRepository.java, src/main/java/com/ll/TeamSteam/domain/notification/service/NotificationService.java, src/main/java/com/ll/TeamSteam/domain/user/repository/UserRepository.java, src/main/java/com/ll/TeamSteam/global/event/EventAfterInvite.java, src/main/java/com/ll/TeamSteam/global/init/NotProd.java, src/main/java/com/ll/TeamSteam/global/rq/Rq.java, src/main/java/com/ll/TeamSteam/standard/Ut.java, src/main/resources/templates/common/layout.html, src/main/resources/templates/main/home.html, src/main/resources/templates/notification/list.html
=> Feature/32 초대 기능 구체화 및 수락/거절 로직 구현

src/main/java/com/ll/TeamSteam/domain/chatRoom/controller/ChatRoomController.java, src/main/java/com/ll/TeamSteam/domain/chatRoom/entity/ChatRoom.java, src/main/java/com/ll/TeamSteam/domain/chatRoom/service/ChatRoomService.java, src/main/java/com/ll/TeamSteam/domain/notification/repository/NotificationRepository.java, src/main/java/com/ll/TeamSteam/domain/notification/service/NotificationService.java, src/main/java/com/ll/TeamSteam/domain/user/dto/UserDto.java, src/main/java/com/ll/TeamSteam/domain/user/service/UserService.java, src/main/resources/static/app.js, src/main/resources/templates/chat/inviteList.html
---
userService에 findAll 추가하였습니다.
=> ref/35 invite로직 리팩토링, 버그 수정

src/main/java/com/ll/TeamSteam/domain/chatRoom/controller/ChatRoomController.java, src/main/java/com/ll/TeamSteam/domain/chatRoom/entity/ChatRoom.java, src/main/java/com/ll/TeamSteam/domain/chatRoom/service/ChatRoomService.java, src/main/resources/templates/chat/inviteList.html
=> feat : 토스트 알림 적용

src/main/resources/templates/chat/room.html
=> Bug/50 채팅 줄바꿈 오류 수정

src/main/java/com/ll/TeamSteam/domain/chatRoom/entity/ChatRoom.java, src/main/java/com/ll/TeamSteam/domain/matching/controller/MatchingController.java, src/main/java/com/ll/TeamSteam/domain/matching/entity/Matching.java, src/main/java/com/ll/TeamSteam/domain/matching/service/MatchingService.java, src/main/resources/application-prod.yml, src/main/resources/templates/matching/detail.html, src/main/resources/templates/matching/modify.html
=> ref/59 매칭 글 수정, orphanRemoval 설정

src/main/java/com/ll/TeamSteam/global/config/WebSocketConfig.java, src/main/resources/application-test.yml
=> Refactoring/61 배포 준비

src/main/java/com/ll/TeamSteam/domain/user/controller/UserController.java, src/main/resources/templates/user/login.html
=> refactor : 배포환경 링크추가

src/main/java/com/ll/TeamSteam/domain/chatRoom/controller/ChatRoomController.java
=> bug/68 redirect url 수정

src/main/java/com/ll/TeamSteam/domain/matching/controller/MatchingController.java, src/main/java/com/ll/TeamSteam/domain/matching/entity/Matching.java, src/main/java/com/ll/TeamSteam/domain/matching/service/MatchingService.java, src/main/java/com/ll/TeamSteam/domain/matchingTag/entity/MatchingTag.java, src/main/java/com/ll/TeamSteam/domain/user/controller/UserController.java, src/main/java/com/ll/TeamSteam/domain/user/service/UserService.java, src/main/java/com/ll/TeamSteam/global/init/NotProd.java, src/main/resources/templates/common/layout.html, src/main/resources/templates/matching/create.html, src/main/resources/templates/matching/list.html
close #70 
- 매칭 게임,장르태그 추가
- 매칭 리스트에 이미지 추가
- 로그아웃 추가
- 매칭 수정
- 매칭 파트너, 최근 함께한 유저
=> feat/70 매칭 게임,장르태그 추가, 이미지 추가

src/test/java/com/ll/TeamSteam/TeamSteamApplicationTests.java
=> Bug/75 ActiveProfile test 추가

Dockerfile, src/main/java/com/ll/TeamSteam/domain/steam/repository/SteamGameLibraryRepository.java, src/main/java/com/ll/TeamSteam/domain/user/controller/UserController.java, src/main/java/com/ll/TeamSteam/domain/user/service/UserService.java, src/main/resources/templates/common/layout.html, src/main/resources/templates/user/profile.html
Close #77 
---------
UserService - transactional이 올바르게 선언됐는지 한번 확인해주시면 감사하겠습니다🙈
몇군데 transactional을 넣어줬더니 라이브러리 불러오는 부분에서 유의미한 속도상승이 있었습니다
=> Feature/78 마이프로필 수정

Dockerfile, src/main/java/com/ll/TeamSteam/domain/user/controller/UserController.java, src/main/resources/application-prod.yml, src/main/resources/application.yml, src/main/resources/static/resource/common/common.css, src/main/resources/templates/common/layout.html, src/main/resources/templates/user/login.html
=> Refactoring/80 로그인UI 적용 및 baseUrl 적용

src/main/java/com/ll/TeamSteam/domain/user/controller/UserController.java
=> Bug/84 로그인 URL 경로 수정

src/main/java/com/ll/TeamSteam/domain/matching/controller/MatchingController.java, src/main/java/com/ll/TeamSteam/domain/matching/entity/Matching.java, src/main/java/com/ll/TeamSteam/domain/matching/service/MatchingService.java, src/main/java/com/ll/TeamSteam/domain/user/controller/UserController.java, src/main/resources/templates/matching/modify.html
=> Ref/83 매칭 수정 기능 리팩토링

src/main/java/com/ll/TeamSteam/global/security/UserInfoResponse.java, src/main/resources/templates/common/layout.html, src/main/resources/templates/user/profile.html
close #86 
- 마이페이지UI수정,
- 레이아웃에 프로필추가
- 프로필페이지 레이아웃 충돌 수정
- 친구 추가 시 알람띄워주기(수락)
- 명예의 전당
=> Design/86 마이페이지UI수정, 레이아웃에 프로필추가

src/main/java/com/ll/TeamSteam/domain/notification/controller/NotificationController.java, src/main/java/com/ll/TeamSteam/domain/notification/eventListener/NotificationEventListenerFriendAdd.java, src/main/java/com/ll/TeamSteam/domain/notification/service/NotificationService.java, src/main/java/com/ll/TeamSteam/domain/user/controller/UserController.java, src/main/java/com/ll/TeamSteam/domain/user/service/UserService.java, src/main/java/com/ll/TeamSteam/global/event/EventAfterFriendAdd.java, src/main/java/com/ll/TeamSteam/global/init/NotProd.java, src/main/resources/templates/user/profile.html
--------
추가 확인된 사항으로 이미 친구일 때도 알림이 가게 설정되어있습니다
=> Feature/87 친구신청을 통한 알림생성

src/main/resources/templates/common/layout.html, src/main/resources/templates/main/home.html, src/main/resources/templates/matching/list.html
=> Design/97 검색창 추가 및 홈화면 배너 수정

src/main/java/com/ll/TeamSteam/domain/chatRoom/controller/ChatRoomController.java, src/main/java/com/ll/TeamSteam/domain/chatRoom/service/ChatRoomService.java, src/main/java/com/ll/TeamSteam/domain/matching/controller/MatchingController.java, src/main/java/com/ll/TeamSteam/domain/matching/entity/SearchQuery.java, src/main/java/com/ll/TeamSteam/domain/matching/repository/MatchingRepository.java, src/main/java/com/ll/TeamSteam/domain/matching/service/MatchingService.java, src/main/java/com/ll/TeamSteam/domain/matchingPartner/service/MatchingPartnerService.java, src/main/java/com/ll/TeamSteam/global/init/NotProd.java, src/main/java/com/ll/TeamSteam/global/rq/Rq.java, src/main/resources/templates/chat/userList.html, src/main/resources/templates/common/js.html, src/main/resources/templates/matching/list.html
=> feat/103 제목 검색

src/main/java/com/ll/TeamSteam/domain/chatRoom/controller/ChatRoomController.java, src/main/java/com/ll/TeamSteam/domain/chatRoom/service/ChatRoomService.java, src/main/java/com/ll/TeamSteam/domain/matching/controller/MatchingController.java, src/main/java/com/ll/TeamSteam/domain/notification/controller/NotificationController.java, src/main/resources/templates/chat/inviteList.html
=> ref/106 채팅방 URL 입장 시 예외처리

src/main/java/com/ll/TeamSteam/domain/matching/controller/MatchingController.java, src/main/java/com/ll/TeamSteam/global/init/NotProd.java, src/main/resources/templates/matching/list.html
=> feat/108 페이지 처리 구현

src/main/java/com/ll/TeamSteam/domain/matching/controller/MatchingController.java, src/main/java/com/ll/TeamSteam/domain/matchingPartner/repository/MatchingPartnerRepository.java, src/main/java/com/ll/TeamSteam/domain/matchingPartner/service/MatchingPartnerService.java, src/main/java/com/ll/TeamSteam/domain/recentlyUser/entity/RecentlyUser.java, src/main/java/com/ll/TeamSteam/domain/recentlyUser/repository/RecentlyUserRepository.java, src/main/java/com/ll/TeamSteam/domain/recentlyUser/service/RecentlyUserService.java, src/main/java/com/ll/TeamSteam/domain/user/controller/UserController.java, src/main/resources/templates/user/profile.html
close #102 
- RecentlyUser 추가
- 자기 자신을 최근 매칭한 유저에 추가하는 오류 수정
-  두 번 추가 안되게 검증
=> feat : RecentlyUser 추가

src/main/java/com/ll/TeamSteam/domain/user/controller/UserController.java, src/main/resources/templates/user/profile.html
- 프로필에서 최근 매칭유저 매너온도 추가
- 페이징처리(게임라이브러리->게임태그저장 , 프로필에서 게임라이브러리 ) 
- 친구삭제 추가
=> design : 프로필에서 최근 매칭유저 매너온도 추가

src/main/java/com/ll/TeamSteam/global/init/NotProd.java
=> bug : confilt로 인한 빌드 오류

src/main/java/com/ll/TeamSteam/domain/chatRoom/service/ChatRoomService.java, src/main/java/com/ll/TeamSteam/domain/matching/controller/MatchingController.java, src/main/java/com/ll/TeamSteam/domain/matching/entity/Matching.java, src/main/java/com/ll/TeamSteam/domain/matching/service/MatchingService.java, src/main/resources/templates/matching/detail.html, src/main/resources/templates/matching/modify.html
=> feat/121 필터링 버그 수정 및 기능 추가

src/main/java/com/ll/TeamSteam/domain/chatRoom/service/ChatRoomService.java, src/main/java/com/ll/TeamSteam/domain/matching/controller/MatchingController.java, src/main/java/com/ll/TeamSteam/domain/matching/entity/Matching.java, src/main/java/com/ll/TeamSteam/domain/matching/repository/MatchingRepository.java, src/main/java/com/ll/TeamSteam/domain/matching/service/MatchingService.java, src/main/java/com/ll/TeamSteam/domain/matchingPartner/entity/MatchingPartner.java, src/main/java/com/ll/TeamSteam/domain/matchingPartner/repository/MatchingPartnerRepository.java, src/main/java/com/ll/TeamSteam/domain/matchingPartner/service/MatchingPartnerService.java, src/main/java/com/ll/TeamSteam/domain/matchingTag/entity/GenreTagType.java, src/main/java/com/ll/TeamSteam/domain/recentlyUser/entity/RecentlyUser.java, src/main/java/com/ll/TeamSteam/global/init/NotProd.java, src/main/java/com/ll/TeamSteam/global/rsData/RsData.java
=> bug/130 ChatRoom, Matching 관련 버그 수정

src/main/java/com/ll/TeamSteam/global/init/NotProd.java, src/test/java/com/ll/TeamSteam/domain/chatRoom/controller/ChatRoomControllerTest.java
=> bug/134 테스트코드 실패로 젠킨스 빌드 오류

src/main/java/com/ll/TeamSteam/domain/friend/repository/FriendRepository.java, src/main/java/com/ll/TeamSteam/domain/steam/service/SteamService.java, src/main/java/com/ll/TeamSteam/domain/user/controller/UserController.java, src/main/java/com/ll/TeamSteam/domain/user/service/UserService.java, src/main/resources/templates/user/createGameTag.html, src/main/resources/templates/user/profile.html
close #128 
- 게임태그 저장페이지 페이징처리
- 친구삭제 기능 추가
- 프로필 게임라이브러리 페이징처리
- 게임태그 저장페이지 UI 수정
- 프로필 게임라이브러리 UI 수정
- 게임태그 저장안되는 버그수정
- 친구삭제
- 게임태그 저장페이지 
- 프로필
=> Feature/128 페이징처리 및 친구삭제 기능 추가

src/main/java/com/ll/TeamSteam/domain/rank/controller/RankController.java, src/main/java/com/ll/TeamSteam/domain/rank/service/RankService.java, src/main/java/com/ll/TeamSteam/domain/user/controller/UserController.java, src/main/java/com/ll/TeamSteam/domain/user/repository/UserRepository.java, src/main/java/com/ll/TeamSteam/global/init/NotProd.java, src/main/resources/templates/common/layout.html, src/main/resources/templates/rank/rank.html
close #129 
------
특이사항으로 pull했을 때 NotProd충돌로 해결 후 머지했습니다.
=> feat/129 명예의전당 페이지 구현

src/main/java/com/ll/TeamSteam/domain/chatRoom/service/ChatRoomService.java, src/main/resources/templates/chat/room.html
=> feat/138 채팅방 owner는 나가기 못하도록 설정

src/main/java/com/ll/TeamSteam/domain/home/HomeController.java, src/main/java/com/ll/TeamSteam/domain/matching/controller/MatchingController.java, src/main/java/com/ll/TeamSteam/domain/matching/entity/Matching.java, src/main/java/com/ll/TeamSteam/domain/matching/service/MatchingService.java, src/main/resources/templates/main/home.html
=> Feature/137 메인 페이지에 정렬 기능 추가

src/test/java/com/ll/TeamSteam/domain/chatRoom/controller/ChatRoomControllerTest.java
=> bug/144 testCode 버그 잠시 주석

src/main/java/com/ll/TeamSteam/domain/home/HomeController.java, src/main/java/com/ll/TeamSteam/domain/matching/controller/MatchingController.java, src/main/java/com/ll/TeamSteam/domain/matching/entity/Matching.java, src/main/java/com/ll/TeamSteam/domain/matching/service/MatchingService.java, src/main/resources/static/resource/common/common.css, src/main/resources/templates/main/home.html
**메인 페이지**
- 레이아웃 적용 안되는 부분 수정
=> Feature/137 메인 페이지 레이아웃 수정

src/main/java/com/ll/TeamSteam/domain/miniGame/controller/MiniGameController.java, src/main/java/com/ll/TeamSteam/domain/miniGame/dto/ScoreRequest.java, src/main/java/com/ll/TeamSteam/domain/miniGame/entity/MiniGame.java, src/main/java/com/ll/TeamSteam/domain/miniGame/repository/MiniGameRepository.java, src/main/java/com/ll/TeamSteam/domain/miniGame/service/MiniGameService.java, src/main/resources/static/minigame/js/minigame.js, src/main/resources/static/minigame/style/minigame.css, src/main/resources/templates/minigame/index.html
=> feat/147 로그인한 유저의 avatar 받아오기

src/main/java/com/ll/TeamSteam/domain/matching/controller/MatchingController.java, src/main/java/com/ll/TeamSteam/domain/matching/entity/Matching.java, src/main/java/com/ll/TeamSteam/domain/matching/service/MatchingService.java, src/main/resources/templates/matching/create.html, src/main/resources/templates/matching/modify.html
=> Feature/156 매칭 수정 시 마감 시간 변경 기능 구현

src/main/resources/templates/main/home.html, src/main/resources/templates/matching/detail.html, src/main/resources/templates/matching/list.html
close #164 
**메인 페이지**
**매칭 목록 페이지**
**매칭 상세 페이지**
=> Feature/164 메인 페이지 기능 추가 및 매칭 목록, 상세 페이지 UI 수정

src/main/java/com/ll/TeamSteam/domain/matching/entity/Matching.java, src/main/resources/templates/matching/detail.html
=> Design/171 매칭 상세 UI 수정

src/main/java/com/ll/TeamSteam/domain/matching/controller/MatchingController.java, src/main/resources/templates/main/home.html, src/main/resources/templates/matching/create.html, src/main/resources/templates/matching/detail.html, src/main/resources/templates/matching/list.html
=> ref/180 createForm 검증 로직, 글자 수 제한

src/main/java/com/ll/TeamSteam/domain/chatRoom/service/ChatRoomService.java
close #183 
---
기존에는 방 생성 시 ROOMIN으로 설정하였는데 방 인원 수 제한보다 인원이 많이 들어가게 되는 버그가 생겨서 수정하였습니다.
=> bug/183 방장은 매칭 생성 시 COMMON 타입

src/main/resources/templates/matching/create.html, src/main/resources/templates/matching/detail.html, src/main/resources/templates/matching/modify.html, src/main/resources/templates/rank/rank.html, src/main/resources/templates/user/createGenre.html, src/main/resources/templates/user/login.html
Close #186 
--------
어색한 타이틀명을 임시로 변경했습니다.
변경된 타이틀파일은 다음과 같습니다.
rank.html
createGenre.html
login.html
수정 화면에서 기존에는 게임태그 자체가 안보이도록 되어있었는데, 지금은 게임태그는 불러오되 disabled처리를 하는게 어떨지 의견을 듣고 싶습니다.
시간태그 추가했습니다
=> Refactoring/186 modify.html, detail.html, 타이틀명 수정

src/main/resources/templates/user/profile.html
=> design : 프로필가는버튼

src/main/java/com/ll/TeamSteam/domain/matching/controller/MatchingController.java, src/main/resources/templates/matching/detail.html, src/main/resources/templates/matching/modify.html
=> Bug/188 미니 프로필 버그 수정 및 자잘한 버그 수정

src/main/java/com/ll/TeamSteam/global/init/NotProd.java, src/test/java/com/ll/TeamSteam/domain/chatRoom/controller/ChatRoomControllerTest.java
=> testCode : Chat관련 테스트 코드 작성

src/main/generated/com/ll/TeamSteam/domain/dm/entity/QDm.java, src/main/generated/com/ll/TeamSteam/domain/dmMessage/entity/QDmMessage.java, src/main/generated/com/ll/TeamSteam/domain/dmUser/entity/QDmUser.java, src/main/java/com/ll/TeamSteam/domain/dm/controller/DmController.java, src/main/java/com/ll/TeamSteam/domain/dm/dto/DmDto.java, src/main/java/com/ll/TeamSteam/domain/dm/entity/Dm.java, src/main/java/com/ll/TeamSteam/domain/dm/exception/NoDmException.java, src/main/java/com/ll/TeamSteam/domain/dm/repository/DmRepository.java, src/main/java/com/ll/TeamSteam/domain/dm/service/DmService.java, src/main/java/com/ll/TeamSteam/domain/dmMessage/controller/DmMessageController.java, src/main/java/com/ll/TeamSteam/domain/dmMessage/dto/DmMessageDto.java, src/main/java/com/ll/TeamSteam/domain/dmMessage/dto/request/DmMessageRequest.java, src/main/java/com/ll/TeamSteam/domain/dmMessage/dto/response/DmResponse.java, src/main/java/com/ll/TeamSteam/domain/dmMessage/dto/response/DmSignalType.java, src/main/java/com/ll/TeamSteam/domain/dmMessage/entity/DmMessage.java, src/main/java/com/ll/TeamSteam/domain/dmMessage/repository/DmMessageRepository.java, src/main/java/com/ll/TeamSteam/domain/dmMessage/service/DmMessageService.java, src/main/java/com/ll/TeamSteam/domain/dmUser/entity/DmUser.java, src/main/java/com/ll/TeamSteam/domain/dmUser/repository/DmUserRepository.java, src/main/java/com/ll/TeamSteam/domain/dmUser/service/DmUserService.java, src/main/java/com/ll/TeamSteam/global/error/GlobalExceptionHandler.java, src/main/resources/static/dm.js, src/main/resources/templates/dm/dmRoom.html, src/main/resources/templates/user/profile.html
=> TS-4 Dm 구현

src/test/java/com/ll/TeamSteam/domain/matching/service/MatchingServiceTest.java
**MatchingServiceTest**
- 매칭 글 작성
- 매칭 마감시간 계산
- 글 작성 시 'N시간 후' 선택에 따른 마감시간 설정
- 매칭 글 수정
=> TS-9 매칭 관련 테스트코드 추가

src/main/java/com/ll/TeamSteam/domain/dm/controller/DmController.java, src/main/java/com/ll/TeamSteam/domain/dm/service/DmService.java, src/test/java/com/ll/TeamSteam/domain/chatRoom/controller/ChatRoomControllerTest.java, src/test/java/com/ll/TeamSteam/domain/chatRoom/service/ChatRoomServiceTest.java, src/test/java/com/ll/TeamSteam/domain/dm/service/DmServiceTest.java
=> TS-13 DM 테스트코드 작성

docker-compose.yml
=> TS-20 docker-compose.yml 수정

docker-compose.yml
=> TS-23 프로메테우스 수정

src/main/java/com/ll/TeamSteam/domain/matching/entity/CreateForm.java, src/test/java/com/ll/TeamSteam/domain/matching/controller/MatchingControllerTest.java
- 매칭 등록 시 제목, 내용 입력칸에 기본값이 자동으로 입력되어있는 상태를 수정하였습니다.
=> TS-22 매칭 등록 폼 UI 수정

src/main/java/com/ll/TeamSteam/domain/user/controller/UserController.java
=> TS-8 로그인 버그 수정

src/main/java/com/ll/TeamSteam/domain/chatMessage/dto/ChatMessageDto.java, src/main/java/com/ll/TeamSteam/domain/chatMessage/entity/ChatMessage.java, src/main/java/com/ll/TeamSteam/domain/chatMessage/service/ChatMessageService.java, src/main/java/com/ll/TeamSteam/domain/user/service/UserService.java
=> TS-25 mongoDB 적용 후 chat 버그 수정

src/main/generated/com/ll/TeamSteam/domain/recentlyUser/entity/QRecentlyUser.java, src/main/java/com/ll/TeamSteam/domain/chatRoom/controller/ChatRoomController.java, src/main/java/com/ll/TeamSteam/domain/matching/controller/MatchingController.java, src/main/java/com/ll/TeamSteam/domain/recentlyUser/entity/RecentlyUser.java, src/main/java/com/ll/TeamSteam/domain/recentlyUser/repository/RecentlyUserRepository.java, src/main/java/com/ll/TeamSteam/domain/recentlyUser/service/RecentlyUserService.java, src/main/resources/templates/user/profile.html
=> TS-27 recentlyUser 버그 수정

src/main/java/com/ll/TeamSteam/domain/recentlyUser/repository/RecentlyUserRepository.java, src/main/java/com/ll/TeamSteam/domain/recentlyUser/service/RecentlyUserService.java, src/test/java/com/ll/TeamSteam/domain/recentlyUser/service/RecentlyUserServiceTest.java
=> TS-33 recentlyUser 버그 2차 수정

src/main/generated/com/ll/TeamSteam/domain/matching/entity/QMatching.java, src/main/java/com/ll/TeamSteam/domain/matching/controller/MatchingController.java, src/main/java/com/ll/TeamSteam/domain/matching/entity/CreateForm.java, src/main/java/com/ll/TeamSteam/domain/matching/entity/Matching.java, src/main/java/com/ll/TeamSteam/domain/matching/service/MatchingService.java, src/main/java/com/ll/TeamSteam/global/init/NotProd.java, src/main/resources/templates/matching/create.html, src/main/resources/templates/matching/detail.html, src/main/resources/templates/matching/modify.html, src/test/java/com/ll/TeamSteam/domain/chatRoom/service/ChatRoomServiceTest.java, src/test/java/com/ll/TeamSteam/domain/matching/service/MatchingServiceTest.java
=> TS-35 matching mic 항목 추가

src/main/java/com/ll/TeamSteam/domain/home/HomeController.java, src/main/java/com/ll/TeamSteam/domain/matching/repository/MatchingRepository.java, src/main/java/com/ll/TeamSteam/domain/matching/service/MatchingService.java, src/main/resources/static/app.js, src/main/resources/templates/chat/userList.html, src/main/resources/templates/main/home.html, src/main/resources/templates/matching/detail.html, src/main/resources/templates/matching/list.html
=> TS-29 글쓴이 필터 추가, chatMessage 시간 버그 수정

src/main/resources/static/layout.css, src/main/resources/templates/common/layout.html
=> Ts-39 네비바 우측 아이콘 수정

src/main/java/com/ll/TeamSteam/domain/chatRoom/controller/ChatRoomController.java, src/main/java/com/ll/TeamSteam/domain/chatRoom/service/ChatRoomService.java, src/main/java/com/ll/TeamSteam/domain/chatUser/repository/ChatUserRepository.java, src/main/java/com/ll/TeamSteam/domain/chatUser/service/ChatUserService.java, src/main/java/com/ll/TeamSteam/domain/dm/controller/DmController.java, src/main/java/com/ll/TeamSteam/domain/dm/repository/DmRepository.java, src/main/java/com/ll/TeamSteam/domain/dm/service/DmService.java, src/main/java/com/ll/TeamSteam/domain/matching/controller/MatchingController.java, src/main/java/com/ll/TeamSteam/domain/notification/controller/NotificationController.java, src/main/java/com/ll/TeamSteam/domain/notification/repository/NotificationRepository.java, src/main/java/com/ll/TeamSteam/domain/notification/service/NotificationService.java, src/main/resources/templates/chat/chatList.html, src/main/resources/templates/common/layout.html, src/main/resources/templates/dm/dmList.html, src/main/resources/templates/matching/list.html, src/main/resources/templates/notification/list.html
=> TS-40 notification 페이지 구현

src/main/generated/com/ll/TeamSteam/domain/notification/entity/QNotification.java, src/main/java/com/ll/TeamSteam/domain/chatRoom/controller/ChatRoomController.java, src/main/java/com/ll/TeamSteam/domain/chatRoom/service/ChatRoomService.java, src/main/java/com/ll/TeamSteam/domain/dm/controller/DmController.java, src/main/java/com/ll/TeamSteam/domain/dm/service/DmService.java, src/main/java/com/ll/TeamSteam/domain/notification/controller/NotificationController.java, src/main/java/com/ll/TeamSteam/domain/notification/entity/Notification.java, src/main/java/com/ll/TeamSteam/domain/notification/eventListener/NotificationEventListener.java, src/main/java/com/ll/TeamSteam/domain/notification/service/NotificationService.java, src/main/java/com/ll/TeamSteam/global/event/EventAfterCreateDm.java, src/main/java/com/ll/TeamSteam/global/event/EventEnterNewChatUser.java, src/main/resources/templates/chat/chatList.html, src/main/resources/templates/dm/dmList.html, src/main/resources/templates/notification/list.html
=> TS-16 생성 시 알림 기능 추가 및 채팅 목록 버그 수정

src/main/java/com/ll/TeamSteam/domain/chatRoom/service/ChatRoomService.java
=> TS-41 채팅방 입장 시 중복으로 알림 발생하는 버그 수정

src/main/resources/templates/main/home.html
=> TS-45  home에 MIC 파싱 안되는 버그 수정

src/main/java/com/ll/TeamSteam/domain/chatRoom/controller/ChatRoomController.java, src/main/java/com/ll/TeamSteam/domain/dm/controller/DmController.java, src/main/java/com/ll/TeamSteam/domain/matching/controller/MatchingController.java
=> TS-46 모집인원 수정

src/main/resources/templates/user/profile.html
=> TS-52 프로필UI 최종 수정

src/main/resources/templates/chat/chatList.html, src/main/resources/templates/common/layout.html, src/main/resources/templates/dm/dmList.html, src/main/resources/templates/user/createGameTag.html, src/main/resources/templates/user/createGenre.html
=> TS-53 전체 UI 디자인 수정, 구글 애드센스 코드 추가

src/main/resources/templates/chat/room.html, src/main/resources/templates/common/layout.html, src/main/resources/templates/dm/dmRoom.html, src/main/resources/templates/matching/detail.html, src/main/resources/templates/user/profile.html
=> design : 프로필 UI 수정, noti 아이콘 알림뱃지 수정, 스크롤바 적용

src/main/java/com/ll/TeamSteam/domain/chatRoom/service/ChatRoomService.java
- ChatUser의 Type이 COMMON인 상태만 필터링 하게 변경
=> TS-60 퇴장한 유저에게도 새 유저 입장 알림 발생되는 버그 수정

build.gradle, src/main/java/com/ll/TeamSteam/domain/chatMessage/service/ChatMessageService.java, src/main/java/com/ll/TeamSteam/domain/dmMessage/service/DmMessageService.java, src/main/java/com/ll/TeamSteam/global/filter/CleanXss.java, src/main/java/com/ll/TeamSteam/global/filter/CrossScriptingFilter.java, src/main/java/com/ll/TeamSteam/global/filter/RequestWrapper.java
---
현재 CrossScriptingFilter 가 존재하는데 이걸로 추후 수정 예정입니다.
web.xml 에 뭐 추가해주면된다는데 안되고 있어 일단은 CleanXss로 대체하였습니다.
```java
public ChatMessage createAndSave(String content, Long userId, Long chatRoomId, ChatMessageType type) {
ChatRoom chatRoom = chatRoomService.findByRoomId(chatRoomId);
String cleanContent = CleanXss.replaceXssAnsSqlInjection(content);
User sender = userService.findById(userId)
.orElseThrow(() -> new IllegalArgumentException("유저아님"));
ChatMessage chatMessage = ChatMessage.create(cleanContent, sender.getId(), sender.getUsername(), sender.getAvatar(), type, chatRoom.getId());
// 글자수 제한
chatMessage.validateLength(chatMessage.getContent());
return chatMessageRepository.save(chatMessage);
}
```
- content가 들어오면 CleanXss에 넣어줘서 replace 시켜줬습니다.
=> TS-57 XSS 스크립트 방어

src/main/resources/templates/user/profile.html
=> TS-61 최근 유저 매너온도 설명 드롭다운 추가

src/main/resources/templates/matching/list.html
=> TS-64 매칭 목록에서 페이지가 없을 때 다음 버튼 제거
